version: '3.8'

services:
  olympus:
    build: .
    container_name: olympus_bot
    restart: unless-stopped
    volumes:
      # Persistencia: Mapear la DB y las sesiones para no perderlas al reiniciar
      - ./olympus.db:/app/olympus.db
      - ./olympus_operations.log:/app/olympus_operations.log
      - ./faucet_bot/sessions:/app/faucet_bot/sessions
      - ./faucet_bot/proxies.txt:/app/faucet_bot/proxies.txt
    environment:
      - TZ=America/Santiago # Configura tu zona horaria
